# Fuente del catálogo: (actual, nivel_actual, nuevo, nivel_nuevo, destino, radix, compone, accion, notas)
# destino: ui | effects | web | mando | cadencia | —   accion: mantener | renombrar | separar | fusionar | mover | extraer | nuevo | absorber
C = [
# ---------- PRIMITIVAS (nuevas) ----------
("—","—","Slot","primitive","ui","Slot","—","nuevo","Lo da Radix; se reexporta para `asChild` en todo el sistema."),
("—","—","VisuallyHidden","primitive","ui","VisuallyHidden","—","nuevo","Sustituye el `clip: rect(0 0 0 0)` repetido en todos los lienzos."),
("—","—","Surface","primitive","ui","Slot","—","nuevo","Material: fondo + borde + radio + sombra. `tone` (default, glass, brand, well, ghost) y `elevation` (flat, low, high). Absorbe ModuleCard --glass, Stat --glass y la tira de Gauge. Implementado como referencia."),
("—","—","Stack / Cluster","primitive","ui","Slot","—","nuevo","Apilado vertical y fila con salto. Elimina los `display:flex; gap` en línea."),
("Title + Eyebrow","átomo","Text / Heading","primitive","ui","Slot","—","fusionar","Una primitiva tipográfica con variantes (`display`, `hero`, `section`, `eyebrow`, `show`, `inverse`)."),
("Divider","átomo","Divider","primitive","ui","Separator","—","mantener","Absorbe `.eg-rule` y `--vertical`."),
("—","—","AspectRatio","primitive","ui","AspectRatio","—","nuevo","Base de PhotoFrame, SelectTile, PreviewFrame y portadas."),
("—","—","Portal","primitive","ui","Portal","—","nuevo","Contenido flotante (menús, diálogos, toasts)."),
("—","—","Label","primitive","ui","Label","—","nuevo","Etiqueta de formulario; la usa Field."),
# ---------- ÁTOMOS ----------
("Button","átomo","Button","atom","ui","Slot","Icon, Spinner","mantener","Pierde `--icon` (pasa a IconButton). Mantiene `.eg-btn-split` como molécula ButtonGroup."),
("IconButton","átomo","IconButton","atom","ui","Slot + AccessibleIcon","Icon","mantener","Gana `shape: square` (antes Button --icon) y `pressed`. Implementado como referencia."),
("—","—","Toggle","atom","ui","Toggle","Icon","nuevo","Botón conmutado (mostrar/ocultar capa, silenciar). IconButton `pressed` puede apoyarse en él."),
("Link","átomo","Link","atom","ui","Slot","—","mantener",""),
("Icon","átomo","Icon","atom","ui","AccessibleIcon","—","mantener","Faltan 14 iconos (ver DECISIONES)."),
("Field (input)","átomo","Input","atom","ui","—","—","extraer","Control nativo; sale de Field. Variante `mono` para código y URLs."),
("Field (textarea)","átomo","Textarea","atom","ui","—","—","extraer","Variantes `code` y `prose` (antes Field --code y --prose)."),
("Field (select)","átomo","Select","atom","ui","Select","Icon","extraer","Select de Radix con el aspecto de Field."),
("`.eg-check`","sin ficha","Checkbox","atom","ui","Checkbox","Icon","extraer","Existía solo como clase."),
("`.eg-check--switch`","sin ficha","Switch","atom","ui","Switch","—","extraer",""),
("Field --range","átomo","Slider","atom","ui","Slider","—","extraer","Tamaño del anillo, umbrales, volumen."),
("—","—","RadioGroup","atom","ui","RadioGroup","—","nuevo","Grupo de opciones exclusivas; base de SelectTile y de chips exclusivos."),
("Chip","átomo","Chip","atom","ui","Toggle / ToggleGroup.Item","Avatar","mantener","Siempre interactivo (filtro o selección). Los grupos van en ChipGroup."),
("Tag + StatusBadge","átomo","Badge","atom","ui","—","Icon","fusionar","Etiqueta estática con `tone` (neutral, info, success, warning, danger, brand) e icono opcional; `solid`."),
("PermissionLevel","átomo (agente)","Badge preset","atom","mando","—","Badge","absorber","Preset de Badge en Mando (read, write, irreversible, blocked)."),
("StatusDot + LiveDot","átomo","StatusDot","atom","ui","—","—","fusionar","LiveDot pasa a `StatusDot state='live'` (con pulso y `--static`)."),
("Kbd","átomo","Kbd","atom","ui","—","—","mantener",""),
("Avatar","átomo","Avatar","atom","ui","Avatar","—","mantener","Radix Avatar da el fallback a iniciales mientras carga la imagen."),
("Logo","átomo","Logo","atom","ui","—","—","mantener",""),
("—","—","ProductMark","atom","ui","—","—","nuevo","Letra o marca de producto con `gradient-btn-primary` + `shadow-btn-primary` (M, C, L, Cr, Mt, Q). Hoy está copiada a mano en cada app."),
("Pixel","átomo","Pixel","atom","web","—","—","mover","Recurso gráfico de la web; revisar si alguna app lo usa."),
("ProgressBar","átomo","ProgressBar","atom","ui","Progress","—","mantener","Radix Progress da `role=progressbar` y los aria-value*."),
("Gauge","átomo","Gauge","atom","ui","Progress (uno por anillo) o role=img","—","mantener","Revisar si exponer cada anillo como Progress o el conjunto como imagen con etiqueta."),
("Stat","átomo","Stat","atom","ui","—","Text","mantener","Pierde `--glass` (usa Surface)."),
("Mark","átomo","Mark","atom","ui","—","—","mantener",""),
("Dropzone","átomo","Dropzone","atom","ui","—","Icon, VisuallyHidden","mantener","Input file nativo oculto con VisuallyHidden."),
("—","—","Tooltip","atom","ui","Tooltip","Portal","nuevo","Hace falta para IconButton, ModuleRail y Gauge. No existe."),
("—","—","Spinner","atom","ui","—","—","nuevo","Carga en Button y estados de espera (Stack & Flow usa spinners-react)."),
("—","—","Skeleton","primitive","ui","—","—","nuevo","Estados de carga de listas y tarjetas (tableros States)."),
# ---------- MOLÉCULAS ----------
("Field","átomo","Field","molecule","ui","Form.Field / Label","Label, Input|Textarea|Select|Slider, Text","separar","Pasa a molécula: etiqueta + control + ayuda + error + contador. El control es un átomo aparte."),
("`.eg-btn-split`","sin ficha","ButtonGroup","molecule","ui","—","Button, IconButton, Menu","extraer","Botón dividido (`--join-start/--join-end`) y grupos de botones."),
("—","—","ChipGroup","molecule","ui","ToggleGroup","Chip","nuevo","Filtros (múltiple) y selección exclusiva (borde de la pantalla en Quorb)."),
("Tabs","molécula","Tabs","molecule","ui","Tabs","Badge (contador)","mantener","`variant`: underline o segmented (Material v2, para 2–4 opciones cortas). Implementado como referencia."),
("MenuList (popup)","molécula","Menu","molecule","ui","DropdownMenu","Icon, Kbd","separar","Menú desplegable con items, separadores, `--danger` y submenús."),
("MenuList --nav","molécula","NavList","molecule","ui","Accordion (grupos) / Collapsible","Icon, Badge, StatusDot","separar","Navegación lateral con grupos plegables, contadores y etiquetas `__tag`."),
("UserMenu","molécula","UserMenu","molecule","ui","DropdownMenu","Avatar, Menu","mantener","Es Menu con Avatar de trigger; podría ser solo un ejemplo de Menu."),
("—","—","Popover","molecule","ui","Popover","Surface, Portal","nuevo","Panel flotante al hacer clic."),
("—","—","HoverCard","molecule","ui","HoverCard","Surface glass, Portal","nuevo","El panel de detalle de Quorb al pasar por un Gauge."),
("Notice","molécula","Notice","molecule","ui","—","Icon, Button","mantener","`role=status` o `alert`. Mantiene `--sm`."),
("—","—","Toast","molecule","ui","Toast","Notice","nuevo","Avisos efímeros (publicado, copiado). No existe."),
("PostCard","molécula","ListItem","molecule","ui","Slot","Surface, Text, Badge, Button","renombrar","Fila/tarjeta genérica con estados (`new`, `failed`, `done`, `empty`, `dragging`, `off`) y `--row`."),
("PostCard (Cadencia)","molécula","PostCard","molecule","cadencia","—","ListItem, Avatar, Chip","mover","Composición de dominio en Cadencia sobre ListItem."),
("SelectTile","molécula","SelectTile","molecule","ui","RadioGroup.Item / ToggleGroup.Item","AspectRatio, Text","mantener","Proporciones como variantes (portrait, story, square, wide, banner)."),
("Timeline","molécula","Timeline","molecule","ui","ScrollArea","Avatar, Badge, Text","mantener","`--chat` para el chat en vivo."),
("—","—","PageHeader","molecule","ui","—","Text, ButtonGroup","nuevo","Eyebrow + título + acciones. Repetido a mano en todas las apps."),
("SectionHeader","molécula","SectionHeader","molecule","ui","—","Text","mantener","Cabecera de sección en registro Show; valorar unificar con PageHeader por `register`."),
("—","—","MeterRow","molecule","ui","Progress","ProgressBar, Text, Gauge key","nuevo","Etiqueta + valor + barra + ayuda (Quorb, egdev-live, Criterio)."),
("ModuleCard","molécula","ModuleCard","molecule","ui","—","Surface, Badge, Button","mantener","`--error`, `--stopped`, `--wide`; `--glass` pasa a Surface."),
("SearchTrigger","molécula","SearchTrigger","molecule","ui","—","Button, Kbd","mantener","Abre CommandPalette."),
("SocialLinks","molécula","SocialLinks","molecule","ui","—","IconButton, Cluster","mantener",""),
("PhotoFrame","molécula","PhotoFrame","molecule","ui","AspectRatio","—","mantener",""),
("PullQuote","molécula","PullQuote","molecule","ui","—","Text","mantener",""),
("Countdown","molécula","Countdown","molecule","ui","—","Text","mantener","También útil en egdev-live."),
("TerminalCard","molécula","TerminalCard","molecule","web","—","Surface","mover","Ficha de perfil de la web."),
("ToolCallChip","molécula (agente)","ToolCallChip","molecule","mando","Collapsible","Badge, StatusDot","mover","Sube a ui si otra app aloja el agente."),
("ConfirmCard","molécula (agente)","ConfirmCard","molecule","mando","Collapsible","Surface, Badge, ButtonGroup","mover","Argumentos crudos en Collapsible."),
("ChatMessage","molécula (agente)","ChatMessage","molecule","mando","—","Avatar, Text","mover",""),
("Composer","molécula (agente)","Composer","molecule","mando","—","Textarea, IconButton, Chip","mover",""),
("NowCard","molécula","NowCard","molecule","web","—","Surface, Text","mover",""),
("ProjectCard","molécula","ProjectCard","molecule","web","—","Surface, Badge, Link","mover",""),
("NoteItem","molécula","NoteItem","molecule","web","—","ListItem","mover","Valorar construirlo sobre ListItem."),
("TipCard","molécula","TipCard","molecule","web","—","AspectRatio, Text","mover",""),
("ArticleFeature","molécula","ArticleFeature","molecule","web","—","PhotoFrame, Text","mover",""),
("ArticleItem","molécula","ArticleItem","molecule","web","—","ListItem","mover",""),
("StreamItem","molécula","StreamItem","molecule","web","—","ListItem","mover",""),
("CommunityCard","molécula","CommunityCard","molecule","web","—","Surface, Avatar, Button","mover",""),
("—","—","Carousel","molecule","ui","— (roving focus propio)","IconButton, ProgressBar","extraer","Sale de TipsSlider: contador, anterior/siguiente, arrastre y teclado."),
# ---------- ORGANISMOS ----------
("Dialog","organismo","Dialog","organism","ui","Dialog","Surface, ButtonGroup, Portal","mantener","Variante `sheet` para paneles laterales (MobileMenu)."),
("—","—","AlertDialog","organism","ui","AlertDialog","Dialog","nuevo","Confirmaciones destructivas (borrar, desconectar)."),
("CommandPalette","organismo","CommandPalette","organism","ui","Dialog (+ cmdk, a confirmar)","Input, ListItem, Kbd","mantener","Radix no tiene combobox; cmdk es la opción habitual sobre Radix Dialog."),
("—","—","Sidebar","organism","ui","ScrollArea","ProductMark, NavList, Text","nuevo","La barra lateral de todas las apps."),
("ModuleRail","organismo (agente)","ModuleRail","organism","ui","Tooltip + NavigationMenu o ToggleGroup","ProductMark, IconButton, StatusDot","mantener","Raíl compacto de Mando; genérico."),
("TabBar","organismo (agente)","TabBar","organism","ui","—","Icon, Badge","mantener","Navegación inferior móvil."),
("Table","organismo","Table","organism","ui","ScrollArea","Checkbox, Switch, Badge, ButtonGroup","mantener","Tabla nativa; orden y selección en el hook."),
("CalendarGrid","organismo","CalendarGrid","organism","ui","— (arrastre: dnd-kit, a confirmar)","ListItem, Text","mantener","`.eg-day` y `.eg-post-row` pasan a partes internas. Falta vista Mes."),
("StageFrame","organismo","PreviewFrame","organism","ui","AspectRatio + Toolbar","IconButton, Chip","renombrar","Vista previa a tamaño fijo con zonas seguras."),
("GaugeStrip","parte de Gauge","GaugeDock","molecule","ui","Toolbar","Surface glass, Gauge","extraer","La tira es un `role=toolbar` con foco itinerante; Radix Toolbar lo da hecho."),
("AgentPanel","organismo (agente)","AgentPanel","organism","mando","ScrollArea","ChatMessage, ToolCallChip, ConfirmCard, Composer","mover",""),
("TopBar","organismo","TopBar","organism","web","NavigationMenu","Logo, SearchTrigger, UserMenu","mover",""),
("MobileMenu","organismo","MobileMenu","organism","web","Dialog (sheet)","NavList, SocialLinks","mover",""),
("SectionNav","organismo","SectionNav","organism","web","—","Link","mover",""),
("Footer","organismo","Footer","organism","web","—","Logo, SocialLinks, Link","mover",""),
("Hero","organismo","Hero","organism","web","—","Text, Button","mover",""),
("ChapterBreak","organismo","ChapterBreak","organism","web","—","Text","mover",""),
("LabStage","organismo","LabStage","organism","web","—","Surface","mover",""),
("Closing","organismo","Closing","organism","web","—","Text, Button","mover",""),
("NotesBoard","organismo","NotesBoard","organism","web","—","SectionHeader, ChipGroup, NoteItem","mover",""),
("NowStrip","organismo","NowStrip","organism","web","—","NowCard","mover",""),
("ProjectsGrid","organismo","ProjectsGrid","organism","web","—","ProjectCard","mover",""),
("BlogGrid","organismo","BlogGrid","organism","web","—","ArticleFeature, ArticleItem","mover",""),
("LiveBand","organismo","LiveBand","organism","web","—","Countdown, PhotoFrame, StreamItem","mover",""),
("CommunityGrid","organismo","CommunityGrid","organism","web","—","CommunityCard","mover",""),
("TipsSlider","organismo","TipsSlider","organism","web","—","Carousel, TipCard","mover","El carrusel genérico sube a ui."),
("AmbientBackground","organismo (efecto)","AmbientBackground","organism","effects","—","—","mover","Canvas de partículas."),
("Isotipo3D","organismo (efecto)","Isotipo3D","organism","effects","—","—","mover","three.js con fallback SVG."),
# ---------- PLANTILLAS ----------
("—","—","AppShell","template","ui","—","Sidebar, ModuleRail, TabBar","nuevo","Barra lateral + contenido; móvil con TabBar. Hoy se repite en las seis apps."),
("SectionShell","plantilla","SectionShell","template","web","—","—","mover",""),
("HomeTemplate","plantilla","HomeTemplate","template","web","—","Secciones web, effects","mover",""),
]
